### ISSUE TITLE
Is there a test.py to calculate accuracy？

### ISSUE THREAD

**Issue by Cui-x** [ojoaobrito/ExplainablePR#1]

**Comment by ojoaobrito** [comment]
@Cui-x Hi! For the CNN I reckon it won't be too difficult to create such script, and as for the interpretability side of things you don't really have an objective way to assess it. It mostly relies on the subjectivity of the viewer. Maybe you could get away with using segmentation masks of the iris, for example, and then seeing if the obtained explanation colors the iris in red tones.
